import StyleDictionary from 'style-dictionary';

// Custom transform to handle Figma color format (remove alpha channel if FF)
StyleDictionary.registerTransform({
  name: 'color/removeAlpha',
  type: 'value',
  filter: (token) => token.type === 'color',
  transform: (token) => {
    const val = token.value;
    // If it's an 8-character hex with FF at the end, remove it
    if (typeof val === 'string' && val.match(/^#[0-9a-fA-F]{6}[fF]{2}$/)) {
      return val.substring(0, 7);
    }
    return val;
  },
});

// Custom transform to convert dimension values to CSS-compatible values
StyleDictionary.registerTransform({
  name: 'size/pxToRem',
  type: 'value',
  transitive: true,
  filter: (token) => {
    return token.type === 'dimension' && typeof token.value === 'number';
  },
  transform: (token) => {
    const val = token.value;
    // Convert px to rem (assuming 16px base)
    return `${val / 16}rem`;
  },
});

// Custom transform for CSS variable names
StyleDictionary.registerTransform({
  name: 'name/cssVar',
  type: 'name',
  transform: (token) => {
    // Convert token path to CSS variable name
    // e.g., color.sys.light.primary -> sys-light-primary
    return token.path.join('-').toLowerCase().replace(/\s+/g, '-');
  },
});

// Custom format for CSS variables
StyleDictionary.registerFormat({
  name: 'css/variables',
  format: ({ dictionary }) => {
    let css =
      '/**\n * Design Tokens\n * Generated by Style Dictionary from Figma\n * DO NOT EDIT DIRECTLY\n */\n\n';

    css += ':root {\n';
    dictionary.allTokens.forEach((token) => {
      const cssVarName = `--${token.name}`;
      const value = token.value;
      css += `  ${cssVarName}: ${value};\n`;
    });
    css += '}\n';

    return css;
  },
});

// Custom format for Tailwind v4 @theme directive
StyleDictionary.registerFormat({
  name: 'tailwind/theme',
  format: ({ dictionary }) => {
    let css = `/**
 * Tailwind v4 Theme Extension
 * Generated by Style Dictionary from Figma
 * DO NOT EDIT DIRECTLY
 */

@theme {
`;

    // Group tokens by category
    const colors = [];
    const fontSize = [];
    const fontWeight = [];
    const lineHeight = [];

    dictionary.allTokens.forEach((token) => {
      const path = token.path;
      const value = token.value;

      // Skip object values
      if (typeof value === 'object' && value !== null) return;

      // COLORS
      if (token.type === 'color') {
        // Simplify color names by removing common design system prefixes
        // Current implementation: Material Design 3 (m3)
        // Note: When switching design systems, update these regex patterns to match
        // your new token naming convention (e.g., for Ant Design, Chakra, etc.)
        let colorKey = path
          .join('-')
          .replace(/^color-[a-z0-9]+-sys-light-/, '')
          .replace(/^color-[a-z0-9]+-sys-dark-/, 'dark-')
          .replace(/^color-[a-z0-9]+-/, '')
          .replace(/^color-/, '');

        colors.push({ key: colorKey, value });
      }

      // FONT SIZES
      if (path.includes('typography') && path[path.length - 1] === 'fontSize') {
        const key = path.slice(2, -1).join('-');
        fontSize.push({ key, value });
      }

      // FONT WEIGHTS
      if (
        path.includes('typography') &&
        path[path.length - 1] === 'fontWeight'
      ) {
        const key = path.slice(2, -1).join('-');
        fontWeight.push({ key, value });
      }

      // LINE HEIGHTS
      if (
        path.includes('typography') &&
        path[path.length - 1] === 'lineHeight'
      ) {
        const key = path.slice(2, -1).join('-');
        lineHeight.push({ key, value });
      }
    });

    // Write colors
    if (colors.length > 0) {
      css += '  /* Colors */\n';
      colors.forEach(({ key, value }) => {
        css += `  --color-${key}: ${value};\n`;
      });
      css += '\n';
    }

    // Write font sizes
    if (fontSize.length > 0) {
      css += '  /* Font Sizes */\n';
      fontSize.forEach(({ key, value }) => {
        css += `  --font-size-${key}: ${value};\n`;
      });
      css += '\n';
    }

    // Write font weights
    if (fontWeight.length > 0) {
      css += '  /* Font Weights */\n';
      fontWeight.forEach(({ key, value }) => {
        css += `  --font-weight-${key}: ${value};\n`;
      });
      css += '\n';
    }

    // Write line heights
    if (lineHeight.length > 0) {
      css += '  /* Line Heights */\n';
      lineHeight.forEach(({ key, value }) => {
        css += `  --line-height-${key}: ${value};\n`;
      });
      css += '\n';
    }

    css += '}\n';
    return css;
  },
});

// Create the Style Dictionary configuration
const config = {
  source: ['tokens/figma-tokens.json'],
  platforms: {
    css: {
      transforms: ['name/cssVar', 'color/removeAlpha', 'size/pxToRem'],
      buildPath: 'tokens/build/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          filter: (token) => {
            // Exclude complex object values that can't be used as CSS variables
            return typeof token.value !== 'object' || token.value === null;
          },
        },
        {
          destination: 'tailwind.theme.css',
          format: 'tailwind/theme',
          filter: (token) => {
            // Only include tokens useful for Tailwind
            return (
              (token.type === 'color' || token.path.includes('typography')) &&
              (typeof token.value !== 'object' || token.value === null)
            );
          },
        },
      ],
    },
  },
};

export default config;
